// <auto-generated />
namespace EmployeesManager.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addKPI : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addKPI));
        
        string IMigrationMetadata.Id
        {
            get { return "202204291449488_addKPI"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
